apiVersion: v1
kind: Secret
metadata:
  name: openedx-external-secrets
  namespace: openedx
type: Opaque
data:
  mysql-password: <base64>
  mongo-password: <base64>
  elasticsearch-password: <base64>
